title: Henrique A. Lavezzo
author: Henrique A. Lavezzo
email: hi@hlavezzo.me
description: >-
  A code alchemist, that loves to write novels, and code transmutation circles.
baseurl: ""
url: "https://hlavezzo.me"
github_username: Rynaro

permalink: /:year/:month/:day/:title
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-babel
  - jemoji

sass:
  load_paths:
    - _sass
    - vendor/css

exclude: ['vendor/bundle', 'node_modules']
