title: Henrique A. Lavezzo
author: Henrique A. Lavezzo
email: me@hlavezzo.run
description: >-
  A code alchemist, that loves to write novels, and code transmutation circles.
baseurl: ""
url: "https://hlavezzo.run"
twitter_username: jekyllrb
github_username:  rynaro

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-babel

sass:
  load_paths:
    - _sass
    - vendor/css

exclude: []
